[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'jesseduffield/lazygit'

[[plugins]]
repo = 'yasukotelin/shirotelin'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'scrooloose/syntastic'
